name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY_SECRET }}

    - name: Build binary
      run: docker run --rm -u root -v ${HOME}/.ssh:/root/.ssh -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent -v `pwd`:/home/rust/src ekidd/rust-musl-builder cargo build --release

    - name: save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rust-musl-builder-gh-actions-private
        path: ./target/x86_64-unknown-linux-musl/release/rust-musl-builder-gh-actions-private